import datetime as dt
import pandas as pd
from rich import print
import sys

'''
This script analyzes a temporary schedule file and prints the per-type 
and total shift loads for each institution.  Run as:

python analyze_schedule <temp_XXX_date.csv>

Temporary schedule file can be either expert or novice.  These files
are generated by generate_assign.py.
'''
    
shift_df = pd.read_csv(sys.argv[1])
ts = shift_df.columns[2:5]
tdfs = {}
for t in ts:
    tdfs[t] = ''
    
for t in tdfs.keys():
    tdfs[t] = shift_df.value_counts(t)
    tdfs[t] = tdfs[t].rename_axis('inst').to_frame()
    tdfs[t] = tdfs[t].rename(columns={'count': t})
    
summary_df = pd.merge(tdfs[ts[0]], tdfs[ts[1]], on='inst', how='outer')
summary_df = pd.merge(summary_df, tdfs[ts[2]], on='inst', how='outer')
summary_df = summary_df.fillna(0)
summary_df['total'] = summary_df[ts[2]] + summary_df[ts[1]] + summary_df[ts[0]]
summary_df = summary_df.sort_values('total')
print(summary_df)
